name = "CamiXon"
uuid = "e90a53f3-3599-4ebe-999f-6f75af03d43f"
authors = ["= <walra356@planet.nl> and contributors"]
version = "1.2.0"

[deps]
#FITSIO = "525bcba6-941b-5504-bd06-fd0dc1a4d2eb"

[compat]
#FITSIO = "0.16"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
